backend:
  name: git-gateway
  branch: main   # شاخه اصلی گیت‌هاب شما

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "همه پست‌ها"
    files:
      - file: "posts.json"
        label: "Posts"
        name: "all_posts"
        fields:
          - name: "id"
            label: "ID"
            widget: "number"
          - name: "date"
            label: "تاریخ"
            widget: "string"
          - name: "title"
            label: "عنوان"
            widget: "object"
            fields:
              - name: "fa"
                label: "عنوان فارسی"
                widget: "string"
              - name: "en"
                label: "عنوان انگلیسی"
                widget: "string"
              - name: "ar"
                label: "عنوان عربی"
                widget: "string"
          - name: "content"
            label: "محتوا"
            widget: "object"
            fields:
              - name: "fa"
                label: "محتوای فارسی"
                widget: "markdown"
              - name: "en"
                label: "محتوای انگلیسی"
                widget: "markdown"
              - name: "ar"
                label: "محتوای عربی"
                widget: "markdown"
          - name: "image"
            label: "عکس"
            widget: "image"
          - name: "link"
            label: "لینک‌ها"
            widget: "object"
            fields:
              - name: "fa"
                label: "لینک فارسی"
                widget: "string"
              - name: "en"
                label: "لینک انگلیسی"
                widget: "string"
              - name: "ar"
                label: "لینک عربی"
                widget: "string"
